# ------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# ------------------------------------

data:
  devices: ['Pcat_Y81C76','RS100S32_Y81C76','RS100S34_Y81C76','R33S32_Y81C76','R33S34_Y81C76','R33S175_Y81C76']
  pretty_devices: ['Pcat-Pcat','R100-S32','R100-S34','R33-S32','R33-S34','R33-S175']
  groups:
    aR: [0, 1, 1, 2, 2, 2]  # LuxR RBS
    aS: [0, 1, 2, 1, 2, 3]  # LasR RBS
  files: ['proc140916.csv','proc140930.csv','proc141006.csv','proc141021.csv','proc141023.csv','proc141028.csv']
  signals: ["OD", "mRFP1", "EYFP", "ECFP"]
  conditions: ["C6","C12"]
  separate_conditions: true
  
model: dr_blackbox

params:
  n_z: 5
  n_y: 2
  n_x: 5
  n_latent_species: 2
  n_hidden_decoder: 25
  n_hidden_decoder_precisions: 20
  lambda_l2: 0.1
  lambda_l2_hidden: 0.1
  learning_boundaries: [250] #,500, 1000]
  learning_rate: 0.005
  learning_gamma: 0.2
  
  constant: { init_x: 0.002, init_rfp: 0.0, init_yfp: 0.0, init_cfp: 0.0 }
  
  # SHARED PARAMETERS
  shared:
    init_data_log_precision:   { distribution: Normal, mu: 5000.0,  sigma: 200.0 }
    standard_normal:           { distribution: Normal, mu: 0.0, sigma: 1.0 }  

  # ============================================================= #
  # GLOBAL PARAMETERS:
  # ============================================================= #
  global:
    x1: { distribution: standard_normal}
    x2: { distribution: standard_normal}
    x3: { distribution: standard_normal}
    x4: { distribution: standard_normal}
    x5: { distribution: standard_normal}

  global_conditioned:
    conditioning: { devices: true, treatments: false }
    y1: { distribution: standard_normal}
    y2: { distribution: standard_normal}

  # ============================================================= #
  # LOCAL PARAMETERS:
  # ============================================================= #
  local:
    conditioning: { devices: true, treatments: false }        
    z1: { distribution: standard_normal}
    z2: { distribution: standard_normal}
    z3: { distribution: standard_normal}
    z4: { distribution: standard_normal}
    z5: { distribution: standard_normal}
    # z6: { distribution: standard_normal}
    # z7: { distribution: standard_normal}
    # z8: { distribution: standard_normal}
    # z9: { distribution: standard_normal}
    # z10: { distribution: standard_normal}
